name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: configure
      run: |
        mkdir -p ./build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
    - name: make
      run: |
        cd build
        cmake --build . --target=all
    - name: test
      run: |
        cd build
        ./las/las-unit
        ./las/las-test-unit
        
